name: go-test-actions
run-name: ${{ github.actor }} GitHub Actions

on:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  go-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19", "1.20", "1.21", "1.22", "1.23"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Display Go version
        run: go version

      - name: Get Dependencies
        run: go mod tidy

      - name: Test
        run: go test -v ./...
